# To update this version, please run
# mise run mise-update <NEW_VERSION>
min_version = "2025.8.6"

[settings]
experimental = true
fetch_remote_versions_timeout = "20s"

[tools]
node = "24.13.1"
pnpm = "10.26.0"
