name: Validate Install

on:
  pull_request:
    branches:
      - main
      - add-eslint

jobs:
  validate-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./web
        run: pnpm install
